[project]
name = "stx-staking-pool"
authors = []
description = ""
telemetry = true
requirements = []
cache_dir = "/home/runner/stx-staking-pool/stx-staking-pool/./.requirements"
boot_contracts = ["pox", "costs-v2", "bns"]
[contracts.stx-staking-pool]
path = "contracts/stx-staking-pool.clar"

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
